package:
  name: gbdraw
  version: 0.1.0

source:
  url: 'https://github.com/yamaton/gbdraw/archive/refs/tags/0.1.0.tar.gz'
  sha256: c14998d7448404d09afd310b7cda4eb67c762b0fed4645ca062641e4b1bdbfd0

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage("gbdraw", max_pin="x.x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pandas
    - fonttools
    - biopython
    - svgwrite
    - cairosvg

channels:
  - conda-forge
  - bioconda
  - defaults

test:
  imports:
    - gbdraw
  commands:
    - gbdraw --help
    - gbdraw circular --help
    - gbdraw linear --help
    - cairosvg --help

about:
  home: "https://github.com/satoshikawato/gbdraw/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "A genome diagram generator for bacterial, archaeal, and viral genomes"
  description: "For details, see https://github.com/satoshikawato/gbdraw/"
  fonts_license: "SIL OFL, Version 1.1"

extra:
  recipe-maintainers:
    - satoshikawato
